// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleRegistrationSystem.Data;

#nullable disable

namespace VehicleRegistrationSystem.Migrations
{
    [DbContext(typeof(VehicleRegistrationDbContext))]
    [Migration("20260328121929_truck kw seeding fixed from 300 to 90 cause of insurance pricing range")]
    partial class truckkwseedingfixedfrom300to90causeofinsurancepricingrange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101010"),
                            Address = "Main Street 12",
                            DateOfBirth = new DateTime(1990, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "John@test.com",
                            FirstName = "John",
                            IdCardNumber = "123456",
                            LastName = "Smith",
                            NationalId = "1234567890123",
                            PhoneNumber = "987654"
                        },
                        new
                        {
                            Id = new Guid("20202020-2020-2020-2020-202020202020"),
                            Address = "Second Street 5",
                            DateOfBirth = new DateTime(2002, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Alice@test.com",
                            FirstName = "Alice",
                            IdCardNumber = "987321",
                            LastName = "Brown",
                            NationalId = "9876543210123",
                            PhoneNumber = "123789"
                        });
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.Insurance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Insurances");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50505050-5050-5050-5050-505050505050"),
                            Name = "Allianz"
                        },
                        new
                        {
                            Id = new Guid("60606060-6060-6060-6060-606060606060"),
                            Name = "Generali"
                        });
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.InsurancePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InsuranceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxKw")
                        .HasColumnType("int");

                    b.Property<int>("MinKw")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerKw")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceId");

                    b.ToTable("InsurancePrices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70707070-7070-7070-7070-707070707070"),
                            InsuranceId = new Guid("50505050-5050-5050-5050-505050505050"),
                            MaxKw = 50,
                            MinKw = 1,
                            PricePerKw = 220m
                        },
                        new
                        {
                            Id = new Guid("80808080-8080-8080-8080-808080808080"),
                            InsuranceId = new Guid("50505050-5050-5050-5050-505050505050"),
                            MaxKw = 100,
                            MinKw = 51,
                            PricePerKw = 270m
                        },
                        new
                        {
                            Id = new Guid("156f70c9-94bf-40e6-ad5b-8efa662f3a22"),
                            InsuranceId = new Guid("60606060-6060-6060-6060-606060606060"),
                            MaxKw = 50,
                            MinKw = 1,
                            PricePerKw = 225m
                        },
                        new
                        {
                            Id = new Guid("8dade321-ff73-43f0-9cf0-2c3ec1ce0700"),
                            InsuranceId = new Guid("60606060-6060-6060-6060-606060606060"),
                            MaxKw = 100,
                            MinKw = 51,
                            PricePerKw = 265m
                        });
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InsuranceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("bit");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RegistrationPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("InsuranceId");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasDatabaseName("UQ_Registration_LicensePlate");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Registration_VehicleId");

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90909090-9090-9090-9090-909090909090"),
                            ClientId = new Guid("10101010-1010-1010-1010-101010101010"),
                            ExpirationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsuranceId = new Guid("50505050-5050-5050-5050-505050505050"),
                            IsTemporary = false,
                            LicensePlate = "PG123AB",
                            RegistrationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegistrationPrice = 55000m,
                            VehicleId = new Guid("30303030-3030-3030-3030-303030303030")
                        });
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("EngineCapacity")
                        .HasColumnType("real");

                    b.Property<int>("EnginePowerKw")
                        .HasColumnType("int");

                    b.Property<DateTime>("FirstRegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("int");

                    b.Property<Guid>("VehicleBrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("VehicleBrandId");

                    b.HasIndex("VehicleModelId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30303030-3030-3030-3030-303030303030"),
                            ChassisNumber = "WBAXX12345678901",
                            EngineCapacity = 150f,
                            EnginePowerKw = 35,
                            FirstRegistrationDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Petrol",
                            ProductionYear = 2022,
                            VehicleBrandId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            VehicleModelId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            VehicleTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Weight = 300f
                        },
                        new
                        {
                            Id = new Guid("40404040-4040-4040-4040-404040404040"),
                            ChassisNumber = "JTDBR32E720123456",
                            EngineCapacity = 1800f,
                            EnginePowerKw = 65,
                            FirstRegistrationDate = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Diesel",
                            ProductionYear = 2020,
                            VehicleBrandId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            VehicleModelId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            VehicleTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Weight = 1400f
                        },
                        new
                        {
                            Id = new Guid("50505050-5050-5050-5050-505050505050"),
                            ChassisNumber = "ACAEBF12345678902",
                            EngineCapacity = 4000f,
                            EnginePowerKw = 90,
                            FirstRegistrationDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FuelType = "Diesel",
                            ProductionYear = 2020,
                            VehicleBrandId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            VehicleModelId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            VehicleTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Weight = 4200f
                        });
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.VehicleBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VehicleTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("VehicleBrands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Yamaha",
                            VehicleTypeId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Toyota",
                            VehicleTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "Mercedes",
                            VehicleTypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VehicleBrandId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VehicleBrandId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Corolla",
                            VehicleBrandId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Name = "R1",
                            VehicleBrandId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Name = "Actros",
                            VehicleBrandId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        });
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "A",
                            Name = "Motorcycle"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "B",
                            Name = "Car"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "C",
                            Name = "Truck"
                        });
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.InsurancePrice", b =>
                {
                    b.HasOne("VehicleRegistrationSystem.Models.Domain.Insurance", "Insurance")
                        .WithMany("InsurancePrices")
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insurance");
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.Registration", b =>
                {
                    b.HasOne("VehicleRegistrationSystem.Models.Domain.Client", "Client")
                        .WithMany("Registrations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleRegistrationSystem.Models.Domain.Insurance", "Insurance")
                        .WithMany("Registrations")
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleRegistrationSystem.Models.Domain.Vehicle", "Vehicle")
                        .WithOne("Registration")
                        .HasForeignKey("VehicleRegistrationSystem.Models.Domain.Registration", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Insurance");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.Vehicle", b =>
                {
                    b.HasOne("VehicleRegistrationSystem.Models.Domain.VehicleBrand", "VehicleBrand")
                        .WithMany()
                        .HasForeignKey("VehicleBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehicleRegistrationSystem.Models.Domain.VehicleModel", "VehicleModel")
                        .WithMany()
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehicleRegistrationSystem.Models.Domain.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VehicleBrand");

                    b.Navigation("VehicleModel");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.VehicleBrand", b =>
                {
                    b.HasOne("VehicleRegistrationSystem.Models.Domain.VehicleType", "VehicleType")
                        .WithMany("Brands")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.VehicleModel", b =>
                {
                    b.HasOne("VehicleRegistrationSystem.Models.Domain.VehicleBrand", "VehicleBrand")
                        .WithMany("Models")
                        .HasForeignKey("VehicleBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VehicleBrand");
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.Client", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.Insurance", b =>
                {
                    b.Navigation("InsurancePrices");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.Vehicle", b =>
                {
                    b.Navigation("Registration")
                        .IsRequired();
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.VehicleBrand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("VehicleRegistrationSystem.Models.Domain.VehicleType", b =>
                {
                    b.Navigation("Brands");
                });
#pragma warning restore 612, 618
        }
    }
}
